INSERT INTO `zf_dict_packettype` VALUES (1, 0, 'Web类流量统计（资源在网外）', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 1, 'VoIP类流量统计', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 2, '通用流量类统计', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 3, '访问指定应用的用户统计', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 4, 'Download类分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 5, 'WEB 类流量统计（资源在网内）', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 128, '用户偏好分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 129, '非法路由检测分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 130, '1+N检测结果分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 131, '1+N关键字段分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 132, 'Web信息推送结果上报', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 192, '应用层DDoS异常流量分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 193, 'CP/SP资源服务器分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 194, 'P2P应用流量流向分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 196, '流量流向分析结果上报', 1);
INSERT INTO `zf_dict_packettype` VALUES (1, 198, 'IP 地址流量TOPN流量分析', 1);
INSERT INTO `zf_dict_packettype` VALUES (2, 0, 'HTTP', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 1, 'RTSP', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 2, 'VoIP', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 3, 'FTP', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 4, 'SMTP', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 5, 'POP3', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 6, 'IMAP', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 7, 'DNS', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 8, 'P2P', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 9, 'Game', 2);
INSERT INTO `zf_dict_packettype` VALUES (2, 10, 'IM', 2);
INSERT INTO `zf_dict_packettype` VALUES (3, 0, 'HTTP GET报文关键字段上报', 2);
INSERT INTO `zf_dict_packettype` VALUES (3, 1, 'WLAN 终端类型上报', 2);

commit;