INSERT INTO `zf_dict_messagetype` VALUES (0, '通用参数设置', 1);
INSERT INTO `zf_dict_messagetype` VALUES (1, '流量分析结果上报策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (2, 'Web类流量管理策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (3, 'URL分类批量查询', 0);
INSERT INTO `zf_dict_messagetype` VALUES (4, 'URL分类批量回应', 0);
INSERT INTO `zf_dict_messagetype` VALUES (5, 'VoIP类流量管理策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (6, '通用流量管理策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (7, '通用流量标记策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (8, '访问指定应用的用户统计策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (9, '流量镜像策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (10, '应用自定义策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (11, '骨干网补充通用参数设置', 1);
INSERT INTO `zf_dict_messagetype` VALUES (64, '用户组归属分配策略 ', 0);
INSERT INTO `zf_dict_messagetype` VALUES (65, 'Web信息推送策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (66, '一拖N用户管理策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (67, '应用层DDoS异常流量管理策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (68, '应用层DDoS保护策略对象绑定', 0);
INSERT INTO `zf_dict_messagetype` VALUES (69, '应用流量流向上报策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (70, 'CP/SP资源服务器分析策略', 0);
INSERT INTO `zf_dict_messagetype` VALUES (128, 'AAA信息采集', 0);
INSERT INTO `zf_dict_messagetype` VALUES (129, 'AAA信息下发(用户上线触发)', 0);
INSERT INTO `zf_dict_messagetype` VALUES (130, 'IP地址段用户信息下发', 1);
INSERT INTO `zf_dict_messagetype` VALUES (131, 'AAA信息反查', 0);
INSERT INTO `zf_dict_messagetype` VALUES (133, '用户/应用策略信息下发', 0);
INSERT INTO `zf_dict_messagetype` VALUES (192, 'DPI设备通用信息下发', 0);
INSERT INTO `zf_dict_messagetype` VALUES (193, 'DPI模块心跳信息', 0);
INSERT INTO `zf_dict_messagetype` VALUES (194, 'DPI模块策略同步请求', 0);
INSERT INTO `zf_dict_messagetype` VALUES (195, 'DPI模块策略同步响应', 0);
INSERT INTO `zf_dict_messagetype` VALUES (196, 'DPI设备状态查询请求', 1);
INSERT INTO `zf_dict_messagetype` VALUES (197, 'DPI设备状态查询回应(静态信息)', 0);
INSERT INTO `zf_dict_messagetype` VALUES (198, 'DPI设备状态查询回应(动态信息)', 0);
INSERT INTO `zf_dict_messagetype` VALUES (199, '协议特征库下发策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (200, 'URL分类库更新策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (201, '应用名称对应表更新通知', 1);
INSERT INTO `zf_dict_messagetype` VALUES (202, 'IP地址库下发策略', 1);
INSERT INTO `zf_dict_messagetype` VALUES (203, '信息推送触发网站列表定义', 0);
INSERT INTO `zf_dict_messagetype` VALUES (204, '信息推送触发关键字列表定义', 0);
INSERT INTO `zf_dict_messagetype` VALUES (205, '策略下发Ack', 0);
INSERT INTO `zf_dict_messagetype` VALUES (207, 'HTTP GET报文清洗黑白名单下发策略', 1);


commit;