INSERT INTO `zf_dict_webtype` VALUES (1, '新闻');
INSERT INTO `zf_dict_webtype` VALUES (2, '军事');
INSERT INTO `zf_dict_webtype` VALUES (3, '视频');
INSERT INTO `zf_dict_webtype` VALUES (4, '财经');
INSERT INTO `zf_dict_webtype` VALUES (5, '小说');
INSERT INTO `zf_dict_webtype` VALUES (6, '购物');
INSERT INTO `zf_dict_webtype` VALUES (7, '社交');
INSERT INTO `zf_dict_webtype` VALUES (8, '生活');
INSERT INTO `zf_dict_webtype` VALUES (9, '网页游戏');
INSERT INTO `zf_dict_webtype` VALUES (10, '团购');
INSERT INTO `zf_dict_webtype` VALUES (11, '体育');
INSERT INTO `zf_dict_webtype` VALUES (12, '数码');
INSERT INTO `zf_dict_webtype` VALUES (13, '手机');
INSERT INTO `zf_dict_webtype` VALUES (14, '旅游');
INSERT INTO `zf_dict_webtype` VALUES (15, '汽车');
INSERT INTO `zf_dict_webtype` VALUES (16, '女性');
INSERT INTO `zf_dict_webtype` VALUES (17, '彩票');
INSERT INTO `zf_dict_webtype` VALUES (18, '银行');
INSERT INTO `zf_dict_webtype` VALUES (255, '未知');

commit;